<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8TvSqFn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8TvSqFn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8TvSqFn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8TvSqFn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8TvSqFn\App_KernelDevDebugContainer([
    'container.build_hash' => '8TvSqFn',
    'container.build_id' => '0c9206b9',
    'container.build_time' => 1727335685,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8TvSqFn');
