<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFOP85x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFOP85x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFOP85x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFOP85x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQFOP85x\App_KernelDevDebugContainer([
    'container.build_hash' => 'QFOP85x',
    'container.build_id' => '546b1e0d',
    'container.build_time' => 1727427862,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFOP85x');
